name: billing_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.6+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.20.2
  animated_custom_dropdown: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/MyNavBar/
    - assets/icons/AppBar/
    - assets/icons/Profile/
    - assets/icons/
    - assets/
    
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
    - family: Golos
      fonts:
        - asset: assets/fonts/Golos-Regular.ttf
        - asset: assets/fonts/Golos-Bold.ttf
          weight: 700
